apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-lp-deployment
  namespace: production
  labels:
    app: p-lp
    env: production
spec:
  selector:
    matchLabels:
      app: p-lp
  replicas: 2
  template:
    metadata:
      labels:
        app: p-lp
    spec:
      containers:
        - name: p-lp-pod
          image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: p-lp-service
  namespace: production
  labels:
    app: p-lp
    env: production
spec:
  type: NodePort
  selector:
    app: p-lp
  ports:
    - port: 80
      protocol: TCP
