apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-lp-deployment
  namespace: staging
  labels:
    app: s-lp
    env: staging
spec:
  selector:
    matchLabels:
      app: s-lp
  replicas: 2
  template:
    metadata:
      labels:
        app: s-lp
    spec:
      containers:
        - name: s-lp-pod
          image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: s-lp-service
  namespace: staging
  labels:
    app: s-lp
    env: staging
spec:
  type: NodePort
  selector:
    app: s-lp
  ports:
    - port: 80
      protocol: TCP
